-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "cashAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "qrAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "specialEvent" TEXT;
